version: "3"

networks:
  gitea:
    external: false
    name: gitea

services:
  gitea:
    image: gitea/gitea:1.17.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

# # https://docs.drone.io/server/provider/gitea/
#   drone:
#       volumes:
#           - 'drone:/data'
#       environment:
#           - 'DRONE_GITEA_SERVER=http://gitea:3000'
#           - DRONE_RPC_SECRET=xd
#           - DRONE_SERVER_HOST=localhost
#           - DRONE_SERVER_PROTO=http
#           - DRONE_GITEA_CLIENT_ID=8a2f1340-1d68-44c6-9f69-55cd1d9223b5
#           - DRONE_GITEA_CLIENT_SECRET=gto_p4h4hopyfpduhy7m6fc2kx4vkc6rdczed7gtumczdqpaw7nqchma
#       ports:
#           - '80:80'
#           - '443:443'
#       restart: always
#       container_name: drone
#       networks:
#         - gitea
#       image: 'drone/drone:2'

#   drone-runner-docker:
#       container_name: drone-runner-1
#       image: 'drone/drone-runner-docker:1'
#       depends_on:
#         - drone
#       environment:
#           - DRONE_RPC_PROTO=http
#           - DRONE_RPC_HOST=drone
#           - DRONE_GITEA_CLIENT_ID=8a2f1340-1d68-44c6-9f69-55cd1d9223b5
#           - DRONE_GITEA_CLIENT_SECRET=gto_p4h4hopyfpduhy7m6fc2kx4vkc6rdczed7gtumczdqpaw7nqchma
#           - DRONE_RPC_SECRET=xd
#           - DRONE_RUNNER_CAPACITY=2
#           - DRONE_RUNNER_NAME=my-first-runner
#       # ports:
#       #     - '3000:3000'
#       expose:
#         - '3000:3000'
#       restart: always
#       networks:
#         - gitea
#       volumes:
#         - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  gitea:
    name: gitea
  drone:
    name: drone