apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
  namespace: loki
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: k8s
        static_configs:
        - targets:
            - localhost
          labels:
            job: k8s
            type: minikube
            lol: wut
            __path__: /var/log/**/*.log
      - job_name: k8s-api
        kubernetes_sd_configs:
          - role: pod 

        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod
