apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/cri-dockerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2022-10-26T22:52:49Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: minikube-m02
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: ""
  name: minikube-m02
  resourceVersion: "3020"
  uid: ff4cec2a-e379-4084-be8e-9c3f380c5bbd
spec:
  podCIDR: 10.244.1.0/24
  podCIDRs:
  - 10.244.1.0/24
status:
  addresses:
  - address: 172.18.141.54
    type: InternalIP
  - address: minikube-m02
    type: Hostname
  allocatable:
    cpu: "2"
    ephemeral-storage: 17784752Ki
    hugepages-2Mi: "0"
    memory: 2165996Ki
    pods: "110"
  capacity:
    cpu: "2"
    ephemeral-storage: 17784752Ki
    hugepages-2Mi: "0"
    memory: 2165996Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2022-10-26T23:19:22Z"
    lastTransitionTime: "2022-10-26T22:52:48Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2022-10-26T23:19:22Z"
    lastTransitionTime: "2022-10-26T22:52:48Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2022-10-26T23:19:22Z"
    lastTransitionTime: "2022-10-26T22:52:48Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2022-10-26T23:19:22Z"
    lastTransitionTime: "2022-10-26T22:52:59Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - k8s.gcr.io/etcd@sha256:13f53ed1d91e2e11aac476ee9a0269fdda6cc4874eba903efd40daf50c55eee5
    - k8s.gcr.io/etcd:3.5.3-0
    sizeBytes: 299495233
  - names:
    - gcr.io/google_containers/kube-registry-proxy@sha256:1040f25a5273de0d72c54865a8efd47e3292de9fb8e5353e3fa76736b854f2da
    sizeBytes: 188250982
  - names:
    - k8s.gcr.io/kube-apiserver@sha256:a04609b85962da7e6531d32b75f652b4fb9f5fe0b0ee0aa160856faad8ec5d96
    - k8s.gcr.io/kube-apiserver:v1.24.3
    sizeBytes: 129710737
  - names:
    - k8s.gcr.io/kube-controller-manager@sha256:f504eead8b8674ebc9067370ef51abbdc531b4a81813bfe464abccb8c76b6a53
    - k8s.gcr.io/kube-controller-manager:v1.24.3
    sizeBytes: 119360464
  - names:
    - k8s.gcr.io/kube-proxy@sha256:c1b135231b5b1a6799346cd701da4b59e5b7ef8e694ec7b04fb23b8dbe144137
    - k8s.gcr.io/kube-proxy:v1.24.3
    sizeBytes: 109939784
  - names:
    - kindest/kindnetd@sha256:e2d4d675dcf28a90102ad5219b75c5a0ee096c4321247dfae31dd1467611a9fb
    - kindest/kindnetd:v20220726-ed811e41
    sizeBytes: 61761170
  - names:
    - k8s.gcr.io/kube-scheduler@sha256:e199523298224cd9f2a9a43c7c2c37fa57aff87648ed1e1de9984eba6f6005f0
    - k8s.gcr.io/kube-scheduler:v1.24.3
    sizeBytes: 50989989
  - names:
    - k8s.gcr.io/coredns/coredns@sha256:5b6ec0d6de9baaf3e92d0f66cd96a25b9edbce8716f5f15dcd1a616b3abd590e
    - k8s.gcr.io/coredns/coredns:v1.8.6
    sizeBytes: 46829283
  - names:
    - gcr.io/k8s-minikube/storage-provisioner@sha256:18eb69d1418e854ad5a19e399310e52808a8321e4c441c1dddad8977a0d7a944
    - gcr.io/k8s-minikube/storage-provisioner:v5
    sizeBytes: 31465472
  - names:
    - registry@sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa
    sizeBytes: 26244015
  - names:
    - k8s.gcr.io/pause@sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c
    - k8s.gcr.io/pause:3.7
    sizeBytes: 711184
  - names:
    - k8s.gcr.io/pause@sha256:3d380ca8864549e74af4b29c10f9cb0956236dfb01c40ca076fb6c37253234db
    - k8s.gcr.io/pause:3.6
    sizeBytes: 682696
  nodeInfo:
    architecture: amd64
    bootID: 051b7e46-0504-4b41-b7e6-38d4bdeaa19a
    containerRuntimeVersion: docker://20.10.17
    kernelVersion: 5.10.57
    kubeProxyVersion: v1.24.3
    kubeletVersion: v1.24.3
    machineID: a8388738a82648e787d641d72b63ee58
    operatingSystem: linux
    osImage: Buildroot 2021.02.12
    systemUUID: abfe8dd9-8c66-844d-ba42-884bb32f38ce
