services:
  promtail:
    image: grafana/promtail:2.7.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
    network_mode: host

networks:
  loki:
    name: loki

volumes:
  loki-data:
    name: loki-data