apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hp-volume
  labels:
    type: local
spec:
  storageClassName: "my-default-local-storage"
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
