services:
  gitlab:
    container_name: gitlab
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "gitlab.internal.com"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 222
        letsencrypt['enable'] = false
        nginx['redirect_http_to_https'] = false
        registry_nginx['redirect_http_to_https'] = false
        mattermost_nginx['redirect_http_to_https'] = false
        gitlab_rails['usage_ping_enabled'] = false
    ports:
      - "80:80"
      - "443:443"
      - "222:22"
    volumes:
      - "gitlab-config:/etc/gitlab"
      - "gitlab-logs:/var/log/gitlab"
      - "gitlab-data:/var/opt/gitlab"
    shm_size: '256m'
    networks:
      - gitlab

  dind:
    image: docker:20-dind
    container_name: dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --storage-driver=overlay2
    networks:
      - gitlab

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner
    restart: always

    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://dind:2375
    volumes:
      - "gitlab-runner-config:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 1
    privileged: true
    networks:
      - gitlab

#
#
# uncomment with changed REGISTRATION_TOKEN and valid CI_SERVER_URL
#
# verify active runner at: http://localhost/admin/runners
# you can always restart this container to re-register runner
#
#
  register-runner:
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    restart: 'no'
    depends_on:
      - dind
      - gitlab-runner
      - gitlab
    environment:
      - CI_SERVER_URL=http://localhost
      - REGISTRATION_TOKEN=eC5svVauzg6MWFqsxpBd
    # workoround due to dns name
    privileged: true
    command:
      - register
      - --non-interactive
      - --locked=false
      # - --name=${RUNNER_NAME}
      - --executor=docker
      - --docker-image=docker:20-dind
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    volumes:
      - gitlab-runner-config:/etc/gitlab-runner:z
    networks:
      - gitlab

  registry:
    image: registry:2
    container_name: container-registry
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "registry-data:/var/lib/registry:rw"
    networks:
      - gitlab

networks:
  gitlab:
    name: gitlab

volumes:
  gitlab-config:
    name: gitlab-config
  gitlab-logs:
    name: gitlab-logs
  gitlab-data:
    name: gitlab-data
  gitlab-runner-config:
    name: gitlab-runner-config
  registry-data:
    name: registry-data