services:
  coredns:
    container_name: coredns
    build:
      context: .
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - "coredns:/etc/coredns"


volumes:
  coredns:
    name: coredns
