apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-metallb-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.174.12.253-10.174.12.254
  # - 192.168.10.0/24
  # - fc00:f853:0ccd:e799::/124
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-advertusenent
  namespace: metallb-system
# spec:
#   ipAddressPools:
#     - my-metallb-pool
