version: "3.9"
services:
  portainer:
    container_name: portainer
    image: 'portainer/portainer-ce:2.16.1'
    restart: always
    ports:
      - '8000:8000'
      - '9443:9443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer:/data'
    networks:
      - portainer

  agent:
      image: 'portainer/agent:2.16.1'
      # ports:
      #     - '9001:9001'
      container_name: portainer_agent
      restart: always
      volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
          - '/var/lib/docker/volumes:/var/lib/docker/volumes'
      networks:
        - portainer


volumes:
  portainer:
    name: portainer
networks:
  portainer:
    name: portainer