apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-metallb-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.0.200-192.168.0.254
  # - 192.168.10.0/24
  # - fc00:f853:0ccd:e799::/124
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertusenent
  namespace: metallb-system
spec:
  ipAddressPools:
    - my-metallb-pool
